SELECT count(*) FROM tabla_de_clientes;

SELECT  DISTINCT A.DNI, A.NOMBRE, B.DNI FROM tabla_de_clientes A
INNER JOIN 
facturas b
ON A.DNI = B.DNI;

SELECT  DISTINCT A.DNI, A.NOMBRE, A.CIUDAD,B.DNI FROM tabla_de_clientes A
LEFT JOIN 
facturas b
ON A.DNI = B.DNI
WHERE B.DNI IS NULL;

SELECT  DISTINCT B.DNI, B.NOMBRE, B.CIUDAD,A.DNI FROM facturas A
RIGHT JOIN 
tabla_de_clientes b
ON A.DNI = B.DNI
WHERE A.DNI IS NULL;