SELECT * FROM tabla_de_productos WHERE SABOR LIKE '%MANZANA';
SELECT * FROM tabla_de_productos WHERE SABOR LIKE '%MANZANA'
AND ENVASE ='BOTELLA PET';
SELECT * FROM tabla_de_clientes WHERE NOMBRE LIKE '%ez';
